<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <AssemblyName>Booking_Management_Backend.Migrator</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>Booking_Management_Backend.Migrator</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>
  <ItemGroup>
    <None Update="appsettings.json;log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Abp.Castle.Log4Net" Version="7.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Booking_Management_Backend.Core\Booking_Management_Backend.Core.csproj" />
    <ProjectReference Include="..\Booking_Management_Backend.EntityFrameworkCore\Booking_Management_Backend.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>